apiVersion: v1
kind: Service
metadata:
  name: {{ include "deliverance-tp.workerName" . }}
  labels:
    app.kubernetes.io/name: {{ include "deliverance-tp.name" . }}
    app.kubernetes.io/component: worker
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: {{ include "deliverance-tp.name" . }}
    app.kubernetes.io/component: worker
  ports:
    - name: gossip
      port: {{ .Values.tensorParallel.gossipPort }}
      targetPort: gossip
      protocol: UDP
