package io.teknek.deliverance.safetensors.prompt;

import java.util.List;
import java.util.Optional;

/**
 * The PromptContext is generated by taking the user messages and applying the Prompt template:
 * <p>
 * <|system|>
 * You are a chatbot that writes short correct responses.
 * <p>
 * Symbols have been added that the tokenizer and model use to interpret the message
 */
public class PromptContext {
    private final String prompt;
    private final Optional<List<Tool>> optionalTools;

    public static PromptContext of(String prompt) {
        return new PromptContext(prompt);
    }

    PromptContext(String prompt, Optional<List<Tool>> optionalTools) {
        this.prompt = prompt;
        this.optionalTools = optionalTools;
    }

    PromptContext(String prompt) {
        this.prompt = prompt;
        this.optionalTools = Optional.empty();
    }

    public boolean hasTools() {
        return optionalTools.isPresent();
    }

    public Optional<List<Tool>> getTools() {
        return optionalTools;
    }

    public String getPrompt() {
        return prompt;
    }

    @Override
    public String toString() {
        return "PromptContext{" + "prompt='" + prompt + '\'' + ", optionalTools=" + optionalTools + '}';
    }
}

