// Generated by jextract

package io.teknek.deliverance.tensor.operations.tensor2native;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class Tensor2Native extends Tensor2Native$shared {

    Tensor2Native() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    private static final int TENSOR2_OK = (int)0L;
    /**
     * {@snippet lang=c :
     * enum tensor2_status.TENSOR2_OK = 0
     * }
     */
    public static int TENSOR2_OK() {
        return TENSOR2_OK;
    }
    private static final int TENSOR2_UNSUPPORTED = (int)1L;
    /**
     * {@snippet lang=c :
     * enum tensor2_status.TENSOR2_UNSUPPORTED = 1
     * }
     */
    public static int TENSOR2_UNSUPPORTED() {
        return TENSOR2_UNSUPPORTED;
    }

    private static class tensor2_dot_product_rows_f32_f32 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Tensor2Native.C_INT,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("tensor2_dot_product_rows_f32_f32");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * tensor2_status tensor2_dot_product_rows_f32_f32(float *result, const float *input, const float *weights, int result_rows, int input_start, int input_length, int weight_row_start, int weight_row_count, int result_column_start, int result_stride, int input_stride, int weight_stride)
     * }
     */
    public static FunctionDescriptor tensor2_dot_product_rows_f32_f32$descriptor() {
        return tensor2_dot_product_rows_f32_f32.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * tensor2_status tensor2_dot_product_rows_f32_f32(float *result, const float *input, const float *weights, int result_rows, int input_start, int input_length, int weight_row_start, int weight_row_count, int result_column_start, int result_stride, int input_stride, int weight_stride)
     * }
     */
    public static MethodHandle tensor2_dot_product_rows_f32_f32$handle() {
        return tensor2_dot_product_rows_f32_f32.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * tensor2_status tensor2_dot_product_rows_f32_f32(float *result, const float *input, const float *weights, int result_rows, int input_start, int input_length, int weight_row_start, int weight_row_count, int result_column_start, int result_stride, int input_stride, int weight_stride)
     * }
     */
    public static MemorySegment tensor2_dot_product_rows_f32_f32$address() {
        return tensor2_dot_product_rows_f32_f32.ADDR;
    }

    /**
     * {@snippet lang=c :
     * tensor2_status tensor2_dot_product_rows_f32_f32(float *result, const float *input, const float *weights, int result_rows, int input_start, int input_length, int weight_row_start, int weight_row_count, int result_column_start, int result_stride, int input_stride, int weight_stride)
     * }
     */
    public static int tensor2_dot_product_rows_f32_f32(MemorySegment result, MemorySegment input, MemorySegment weights, int result_rows, int input_start, int input_length, int weight_row_start, int weight_row_count, int result_column_start, int result_stride, int input_stride, int weight_stride) {
        var mh$ = tensor2_dot_product_rows_f32_f32.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tensor2_dot_product_rows_f32_f32", result, input, weights, result_rows, input_start, input_length, weight_row_start, weight_row_count, result_column_start, result_stride, input_stride, weight_stride);
            }
            return (int)mh$.invokeExact(result, input, weights, result_rows, input_start, input_length, weight_row_start, weight_row_count, result_column_start, result_stride, input_stride, weight_stride);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tensor2_dot_product_rows_f32_q8 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Tensor2Native.C_INT,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("tensor2_dot_product_rows_f32_q8");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * tensor2_status tensor2_dot_product_rows_f32_q8(float *result, const float *input, const int8_t *weights, const float *weight_scales, int result_rows, int input_start, int input_length, int weight_row_start, int weight_row_count, int result_column_start, int result_stride, int input_stride, int weight_stride, int weight_scale_stride)
     * }
     */
    public static FunctionDescriptor tensor2_dot_product_rows_f32_q8$descriptor() {
        return tensor2_dot_product_rows_f32_q8.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * tensor2_status tensor2_dot_product_rows_f32_q8(float *result, const float *input, const int8_t *weights, const float *weight_scales, int result_rows, int input_start, int input_length, int weight_row_start, int weight_row_count, int result_column_start, int result_stride, int input_stride, int weight_stride, int weight_scale_stride)
     * }
     */
    public static MethodHandle tensor2_dot_product_rows_f32_q8$handle() {
        return tensor2_dot_product_rows_f32_q8.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * tensor2_status tensor2_dot_product_rows_f32_q8(float *result, const float *input, const int8_t *weights, const float *weight_scales, int result_rows, int input_start, int input_length, int weight_row_start, int weight_row_count, int result_column_start, int result_stride, int input_stride, int weight_stride, int weight_scale_stride)
     * }
     */
    public static MemorySegment tensor2_dot_product_rows_f32_q8$address() {
        return tensor2_dot_product_rows_f32_q8.ADDR;
    }

    /**
     * {@snippet lang=c :
     * tensor2_status tensor2_dot_product_rows_f32_q8(float *result, const float *input, const int8_t *weights, const float *weight_scales, int result_rows, int input_start, int input_length, int weight_row_start, int weight_row_count, int result_column_start, int result_stride, int input_stride, int weight_stride, int weight_scale_stride)
     * }
     */
    public static int tensor2_dot_product_rows_f32_q8(MemorySegment result, MemorySegment input, MemorySegment weights, MemorySegment weight_scales, int result_rows, int input_start, int input_length, int weight_row_start, int weight_row_count, int result_column_start, int result_stride, int input_stride, int weight_stride, int weight_scale_stride) {
        var mh$ = tensor2_dot_product_rows_f32_q8.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tensor2_dot_product_rows_f32_q8", result, input, weights, weight_scales, result_rows, input_start, input_length, weight_row_start, weight_row_count, result_column_start, result_stride, input_stride, weight_stride, weight_scale_stride);
            }
            return (int)mh$.invokeExact(result, input, weights, weight_scales, result_rows, input_start, input_length, weight_row_start, weight_row_count, result_column_start, result_stride, input_stride, weight_stride, weight_scale_stride);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tensor2_dot_product_rows_f32_q4 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Tensor2Native.C_INT,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("tensor2_dot_product_rows_f32_q4");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * tensor2_status tensor2_dot_product_rows_f32_q4(float *result, const float *input, const uint8_t *weights, const float *weight_scales, int result_rows, int input_column_start, int weight_column_start, int column_length, int weight_row_start, int weight_row_count, int result_column_start, int result_stride, int input_stride, int weight_stride, int weight_scale_stride)
     * }
     */
    public static FunctionDescriptor tensor2_dot_product_rows_f32_q4$descriptor() {
        return tensor2_dot_product_rows_f32_q4.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * tensor2_status tensor2_dot_product_rows_f32_q4(float *result, const float *input, const uint8_t *weights, const float *weight_scales, int result_rows, int input_column_start, int weight_column_start, int column_length, int weight_row_start, int weight_row_count, int result_column_start, int result_stride, int input_stride, int weight_stride, int weight_scale_stride)
     * }
     */
    public static MethodHandle tensor2_dot_product_rows_f32_q4$handle() {
        return tensor2_dot_product_rows_f32_q4.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * tensor2_status tensor2_dot_product_rows_f32_q4(float *result, const float *input, const uint8_t *weights, const float *weight_scales, int result_rows, int input_column_start, int weight_column_start, int column_length, int weight_row_start, int weight_row_count, int result_column_start, int result_stride, int input_stride, int weight_stride, int weight_scale_stride)
     * }
     */
    public static MemorySegment tensor2_dot_product_rows_f32_q4$address() {
        return tensor2_dot_product_rows_f32_q4.ADDR;
    }

    /**
     * {@snippet lang=c :
     * tensor2_status tensor2_dot_product_rows_f32_q4(float *result, const float *input, const uint8_t *weights, const float *weight_scales, int result_rows, int input_column_start, int weight_column_start, int column_length, int weight_row_start, int weight_row_count, int result_column_start, int result_stride, int input_stride, int weight_stride, int weight_scale_stride)
     * }
     */
    public static int tensor2_dot_product_rows_f32_q4(MemorySegment result, MemorySegment input, MemorySegment weights, MemorySegment weight_scales, int result_rows, int input_column_start, int weight_column_start, int column_length, int weight_row_start, int weight_row_count, int result_column_start, int result_stride, int input_stride, int weight_stride, int weight_scale_stride) {
        var mh$ = tensor2_dot_product_rows_f32_q4.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tensor2_dot_product_rows_f32_q4", result, input, weights, weight_scales, result_rows, input_column_start, weight_column_start, column_length, weight_row_start, weight_row_count, result_column_start, result_stride, input_stride, weight_stride, weight_scale_stride);
            }
            return (int)mh$.invokeExact(result, input, weights, weight_scales, result_rows, input_column_start, weight_column_start, column_length, weight_row_start, weight_row_count, result_column_start, result_stride, input_stride, weight_stride, weight_scale_stride);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tensor2_dot_product_rows_bf16_q4 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Tensor2Native.C_INT,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("tensor2_dot_product_rows_bf16_q4");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * tensor2_status tensor2_dot_product_rows_bf16_q4(void *result, const uint16_t *input, const uint8_t *weights, const float *weight_scales, int result_bf16, int result_rows, int input_column_start, int weight_column_start, int column_length, int weight_row_start, int weight_row_count, int result_column_start, int result_stride, int input_stride, int weight_stride, int weight_scale_stride)
     * }
     */
    public static FunctionDescriptor tensor2_dot_product_rows_bf16_q4$descriptor() {
        return tensor2_dot_product_rows_bf16_q4.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * tensor2_status tensor2_dot_product_rows_bf16_q4(void *result, const uint16_t *input, const uint8_t *weights, const float *weight_scales, int result_bf16, int result_rows, int input_column_start, int weight_column_start, int column_length, int weight_row_start, int weight_row_count, int result_column_start, int result_stride, int input_stride, int weight_stride, int weight_scale_stride)
     * }
     */
    public static MethodHandle tensor2_dot_product_rows_bf16_q4$handle() {
        return tensor2_dot_product_rows_bf16_q4.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * tensor2_status tensor2_dot_product_rows_bf16_q4(void *result, const uint16_t *input, const uint8_t *weights, const float *weight_scales, int result_bf16, int result_rows, int input_column_start, int weight_column_start, int column_length, int weight_row_start, int weight_row_count, int result_column_start, int result_stride, int input_stride, int weight_stride, int weight_scale_stride)
     * }
     */
    public static MemorySegment tensor2_dot_product_rows_bf16_q4$address() {
        return tensor2_dot_product_rows_bf16_q4.ADDR;
    }

    /**
     * {@snippet lang=c :
     * tensor2_status tensor2_dot_product_rows_bf16_q4(void *result, const uint16_t *input, const uint8_t *weights, const float *weight_scales, int result_bf16, int result_rows, int input_column_start, int weight_column_start, int column_length, int weight_row_start, int weight_row_count, int result_column_start, int result_stride, int input_stride, int weight_stride, int weight_scale_stride)
     * }
     */
    public static int tensor2_dot_product_rows_bf16_q4(MemorySegment result, MemorySegment input, MemorySegment weights, MemorySegment weight_scales, int result_bf16, int result_rows, int input_column_start, int weight_column_start, int column_length, int weight_row_start, int weight_row_count, int result_column_start, int result_stride, int input_stride, int weight_stride, int weight_scale_stride) {
        var mh$ = tensor2_dot_product_rows_bf16_q4.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tensor2_dot_product_rows_bf16_q4", result, input, weights, weight_scales, result_bf16, result_rows, input_column_start, weight_column_start, column_length, weight_row_start, weight_row_count, result_column_start, result_stride, input_stride, weight_stride, weight_scale_stride);
            }
            return (int)mh$.invokeExact(result, input, weights, weight_scales, result_bf16, result_rows, input_column_start, weight_column_start, column_length, weight_row_start, weight_row_count, result_column_start, result_stride, input_stride, weight_stride, weight_scale_stride);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tensor2_dot_product_rows_i8_q4 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Tensor2Native.C_INT,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("tensor2_dot_product_rows_i8_q4");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * tensor2_status tensor2_dot_product_rows_i8_q4(float *result, const int8_t *input, const float *input_scales, const uint8_t *weights, const float *weight_scales, int result_rows, int input_column_start, int weight_column_start, int column_length, int weight_row_start, int weight_row_count, int result_column_start, int result_stride, int input_stride, int input_scale_stride, int weight_stride, int weight_scale_stride)
     * }
     */
    public static FunctionDescriptor tensor2_dot_product_rows_i8_q4$descriptor() {
        return tensor2_dot_product_rows_i8_q4.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * tensor2_status tensor2_dot_product_rows_i8_q4(float *result, const int8_t *input, const float *input_scales, const uint8_t *weights, const float *weight_scales, int result_rows, int input_column_start, int weight_column_start, int column_length, int weight_row_start, int weight_row_count, int result_column_start, int result_stride, int input_stride, int input_scale_stride, int weight_stride, int weight_scale_stride)
     * }
     */
    public static MethodHandle tensor2_dot_product_rows_i8_q4$handle() {
        return tensor2_dot_product_rows_i8_q4.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * tensor2_status tensor2_dot_product_rows_i8_q4(float *result, const int8_t *input, const float *input_scales, const uint8_t *weights, const float *weight_scales, int result_rows, int input_column_start, int weight_column_start, int column_length, int weight_row_start, int weight_row_count, int result_column_start, int result_stride, int input_stride, int input_scale_stride, int weight_stride, int weight_scale_stride)
     * }
     */
    public static MemorySegment tensor2_dot_product_rows_i8_q4$address() {
        return tensor2_dot_product_rows_i8_q4.ADDR;
    }

    /**
     * {@snippet lang=c :
     * tensor2_status tensor2_dot_product_rows_i8_q4(float *result, const int8_t *input, const float *input_scales, const uint8_t *weights, const float *weight_scales, int result_rows, int input_column_start, int weight_column_start, int column_length, int weight_row_start, int weight_row_count, int result_column_start, int result_stride, int input_stride, int input_scale_stride, int weight_stride, int weight_scale_stride)
     * }
     */
    public static int tensor2_dot_product_rows_i8_q4(MemorySegment result, MemorySegment input, MemorySegment input_scales, MemorySegment weights, MemorySegment weight_scales, int result_rows, int input_column_start, int weight_column_start, int column_length, int weight_row_start, int weight_row_count, int result_column_start, int result_stride, int input_stride, int input_scale_stride, int weight_stride, int weight_scale_stride) {
        var mh$ = tensor2_dot_product_rows_i8_q4.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tensor2_dot_product_rows_i8_q4", result, input, input_scales, weights, weight_scales, result_rows, input_column_start, weight_column_start, column_length, weight_row_start, weight_row_count, result_column_start, result_stride, input_stride, input_scale_stride, weight_stride, weight_scale_stride);
            }
            return (int)mh$.invokeExact(result, input, input_scales, weights, weight_scales, result_rows, input_column_start, weight_column_start, column_length, weight_row_start, weight_row_count, result_column_start, result_stride, input_stride, input_scale_stride, weight_stride, weight_scale_stride);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tensor2_saxpy_f32 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Tensor2Native.C_INT,
            Tensor2Native.C_FLOAT,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("tensor2_saxpy_f32");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * tensor2_status tensor2_saxpy_f32(float alpha, const float *x, float *y, int x_offset, int y_offset, int length)
     * }
     */
    public static FunctionDescriptor tensor2_saxpy_f32$descriptor() {
        return tensor2_saxpy_f32.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * tensor2_status tensor2_saxpy_f32(float alpha, const float *x, float *y, int x_offset, int y_offset, int length)
     * }
     */
    public static MethodHandle tensor2_saxpy_f32$handle() {
        return tensor2_saxpy_f32.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * tensor2_status tensor2_saxpy_f32(float alpha, const float *x, float *y, int x_offset, int y_offset, int length)
     * }
     */
    public static MemorySegment tensor2_saxpy_f32$address() {
        return tensor2_saxpy_f32.ADDR;
    }

    /**
     * {@snippet lang=c :
     * tensor2_status tensor2_saxpy_f32(float alpha, const float *x, float *y, int x_offset, int y_offset, int length)
     * }
     */
    public static int tensor2_saxpy_f32(float alpha, MemorySegment x, MemorySegment y, int x_offset, int y_offset, int length) {
        var mh$ = tensor2_saxpy_f32.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tensor2_saxpy_f32", alpha, x, y, x_offset, y_offset, length);
            }
            return (int)mh$.invokeExact(alpha, x, y, x_offset, y_offset, length);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tensor2_saxpy_f32_batch {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Tensor2Native.C_INT,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("tensor2_saxpy_f32_batch");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * tensor2_status tensor2_saxpy_f32_batch(const float *alpha, const float *x, float *y, int x_offset, int y_offset, int length, int alpha_offset, int x_row_offset, int batch_size, int x_stride)
     * }
     */
    public static FunctionDescriptor tensor2_saxpy_f32_batch$descriptor() {
        return tensor2_saxpy_f32_batch.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * tensor2_status tensor2_saxpy_f32_batch(const float *alpha, const float *x, float *y, int x_offset, int y_offset, int length, int alpha_offset, int x_row_offset, int batch_size, int x_stride)
     * }
     */
    public static MethodHandle tensor2_saxpy_f32_batch$handle() {
        return tensor2_saxpy_f32_batch.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * tensor2_status tensor2_saxpy_f32_batch(const float *alpha, const float *x, float *y, int x_offset, int y_offset, int length, int alpha_offset, int x_row_offset, int batch_size, int x_stride)
     * }
     */
    public static MemorySegment tensor2_saxpy_f32_batch$address() {
        return tensor2_saxpy_f32_batch.ADDR;
    }

    /**
     * {@snippet lang=c :
     * tensor2_status tensor2_saxpy_f32_batch(const float *alpha, const float *x, float *y, int x_offset, int y_offset, int length, int alpha_offset, int x_row_offset, int batch_size, int x_stride)
     * }
     */
    public static int tensor2_saxpy_f32_batch(MemorySegment alpha, MemorySegment x, MemorySegment y, int x_offset, int y_offset, int length, int alpha_offset, int x_row_offset, int batch_size, int x_stride) {
        var mh$ = tensor2_saxpy_f32_batch.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tensor2_saxpy_f32_batch", alpha, x, y, x_offset, y_offset, length, alpha_offset, x_row_offset, batch_size, x_stride);
            }
            return (int)mh$.invokeExact(alpha, x, y, x_offset, y_offset, length, alpha_offset, x_row_offset, batch_size, x_stride);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tensor2_batch_dot_f32_f32 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Tensor2Native.C_INT,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("tensor2_batch_dot_f32_f32");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * tensor2_status tensor2_batch_dot_f32_f32(float *result, const float *a, const float *b, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int b_stride)
     * }
     */
    public static FunctionDescriptor tensor2_batch_dot_f32_f32$descriptor() {
        return tensor2_batch_dot_f32_f32.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * tensor2_status tensor2_batch_dot_f32_f32(float *result, const float *a, const float *b, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int b_stride)
     * }
     */
    public static MethodHandle tensor2_batch_dot_f32_f32$handle() {
        return tensor2_batch_dot_f32_f32.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * tensor2_status tensor2_batch_dot_f32_f32(float *result, const float *a, const float *b, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int b_stride)
     * }
     */
    public static MemorySegment tensor2_batch_dot_f32_f32$address() {
        return tensor2_batch_dot_f32_f32.ADDR;
    }

    /**
     * {@snippet lang=c :
     * tensor2_status tensor2_batch_dot_f32_f32(float *result, const float *a, const float *b, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int b_stride)
     * }
     */
    public static int tensor2_batch_dot_f32_f32(MemorySegment result, MemorySegment a, MemorySegment b, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int b_stride) {
        var mh$ = tensor2_batch_dot_f32_f32.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tensor2_batch_dot_f32_f32", result, a, b, result_rows, a_row_offset, a_column_offset, b_column_offset, column_length, result_row_offset, b_row_offset, row_chunk_size, result_stride, a_stride, b_stride);
            }
            return (int)mh$.invokeExact(result, a, b, result_rows, a_row_offset, a_column_offset, b_column_offset, column_length, result_row_offset, b_row_offset, row_chunk_size, result_stride, a_stride, b_stride);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tensor2_batch_dot_f32_bf16 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Tensor2Native.C_INT,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("tensor2_batch_dot_f32_bf16");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * tensor2_status tensor2_batch_dot_f32_bf16(float *result, const float *a, const uint16_t *b, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int b_stride)
     * }
     */
    public static FunctionDescriptor tensor2_batch_dot_f32_bf16$descriptor() {
        return tensor2_batch_dot_f32_bf16.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * tensor2_status tensor2_batch_dot_f32_bf16(float *result, const float *a, const uint16_t *b, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int b_stride)
     * }
     */
    public static MethodHandle tensor2_batch_dot_f32_bf16$handle() {
        return tensor2_batch_dot_f32_bf16.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * tensor2_status tensor2_batch_dot_f32_bf16(float *result, const float *a, const uint16_t *b, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int b_stride)
     * }
     */
    public static MemorySegment tensor2_batch_dot_f32_bf16$address() {
        return tensor2_batch_dot_f32_bf16.ADDR;
    }

    /**
     * {@snippet lang=c :
     * tensor2_status tensor2_batch_dot_f32_bf16(float *result, const float *a, const uint16_t *b, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int b_stride)
     * }
     */
    public static int tensor2_batch_dot_f32_bf16(MemorySegment result, MemorySegment a, MemorySegment b, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int b_stride) {
        var mh$ = tensor2_batch_dot_f32_bf16.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tensor2_batch_dot_f32_bf16", result, a, b, result_rows, a_row_offset, a_column_offset, b_column_offset, column_length, result_row_offset, b_row_offset, row_chunk_size, result_stride, a_stride, b_stride);
            }
            return (int)mh$.invokeExact(result, a, b, result_rows, a_row_offset, a_column_offset, b_column_offset, column_length, result_row_offset, b_row_offset, row_chunk_size, result_stride, a_stride, b_stride);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tensor2_gemm_f32_bf16 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Tensor2Native.C_INT,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("tensor2_gemm_f32_bf16");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * tensor2_status tensor2_gemm_f32_bf16(float *result, const float *a, const uint16_t *b, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int b_stride)
     * }
     */
    public static FunctionDescriptor tensor2_gemm_f32_bf16$descriptor() {
        return tensor2_gemm_f32_bf16.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * tensor2_status tensor2_gemm_f32_bf16(float *result, const float *a, const uint16_t *b, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int b_stride)
     * }
     */
    public static MethodHandle tensor2_gemm_f32_bf16$handle() {
        return tensor2_gemm_f32_bf16.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * tensor2_status tensor2_gemm_f32_bf16(float *result, const float *a, const uint16_t *b, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int b_stride)
     * }
     */
    public static MemorySegment tensor2_gemm_f32_bf16$address() {
        return tensor2_gemm_f32_bf16.ADDR;
    }

    /**
     * {@snippet lang=c :
     * tensor2_status tensor2_gemm_f32_bf16(float *result, const float *a, const uint16_t *b, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int b_stride)
     * }
     */
    public static int tensor2_gemm_f32_bf16(MemorySegment result, MemorySegment a, MemorySegment b, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int b_stride) {
        var mh$ = tensor2_gemm_f32_bf16.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tensor2_gemm_f32_bf16", result, a, b, result_rows, a_row_offset, a_column_offset, b_column_offset, column_length, result_row_offset, b_row_offset, row_chunk_size, result_stride, a_stride, b_stride);
            }
            return (int)mh$.invokeExact(result, a, b, result_rows, a_row_offset, a_column_offset, b_column_offset, column_length, result_row_offset, b_row_offset, row_chunk_size, result_stride, a_stride, b_stride);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tensor2_gemm_f32_q4 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Tensor2Native.C_INT,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("tensor2_gemm_f32_q4");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * tensor2_status tensor2_gemm_f32_q4(float *result, const float *a, const uint8_t *b, const float *b_scales, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int b_stride, int b_scale_stride)
     * }
     */
    public static FunctionDescriptor tensor2_gemm_f32_q4$descriptor() {
        return tensor2_gemm_f32_q4.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * tensor2_status tensor2_gemm_f32_q4(float *result, const float *a, const uint8_t *b, const float *b_scales, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int b_stride, int b_scale_stride)
     * }
     */
    public static MethodHandle tensor2_gemm_f32_q4$handle() {
        return tensor2_gemm_f32_q4.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * tensor2_status tensor2_gemm_f32_q4(float *result, const float *a, const uint8_t *b, const float *b_scales, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int b_stride, int b_scale_stride)
     * }
     */
    public static MemorySegment tensor2_gemm_f32_q4$address() {
        return tensor2_gemm_f32_q4.ADDR;
    }

    /**
     * {@snippet lang=c :
     * tensor2_status tensor2_gemm_f32_q4(float *result, const float *a, const uint8_t *b, const float *b_scales, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int b_stride, int b_scale_stride)
     * }
     */
    public static int tensor2_gemm_f32_q4(MemorySegment result, MemorySegment a, MemorySegment b, MemorySegment b_scales, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int b_stride, int b_scale_stride) {
        var mh$ = tensor2_gemm_f32_q4.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tensor2_gemm_f32_q4", result, a, b, b_scales, result_rows, a_row_offset, a_column_offset, b_column_offset, column_length, result_row_offset, b_row_offset, row_chunk_size, result_stride, a_stride, b_stride, b_scale_stride);
            }
            return (int)mh$.invokeExact(result, a, b, b_scales, result_rows, a_row_offset, a_column_offset, b_column_offset, column_length, result_row_offset, b_row_offset, row_chunk_size, result_stride, a_stride, b_stride, b_scale_stride);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tensor2_gemm_i8_q4 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Tensor2Native.C_INT,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("tensor2_gemm_i8_q4");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * tensor2_status tensor2_gemm_i8_q4(float *result, const int8_t *a, const float *a_scales, const uint8_t *b, const float *b_scales, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int a_scale_stride, int b_stride, int b_scale_stride)
     * }
     */
    public static FunctionDescriptor tensor2_gemm_i8_q4$descriptor() {
        return tensor2_gemm_i8_q4.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * tensor2_status tensor2_gemm_i8_q4(float *result, const int8_t *a, const float *a_scales, const uint8_t *b, const float *b_scales, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int a_scale_stride, int b_stride, int b_scale_stride)
     * }
     */
    public static MethodHandle tensor2_gemm_i8_q4$handle() {
        return tensor2_gemm_i8_q4.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * tensor2_status tensor2_gemm_i8_q4(float *result, const int8_t *a, const float *a_scales, const uint8_t *b, const float *b_scales, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int a_scale_stride, int b_stride, int b_scale_stride)
     * }
     */
    public static MemorySegment tensor2_gemm_i8_q4$address() {
        return tensor2_gemm_i8_q4.ADDR;
    }

    /**
     * {@snippet lang=c :
     * tensor2_status tensor2_gemm_i8_q4(float *result, const int8_t *a, const float *a_scales, const uint8_t *b, const float *b_scales, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int a_scale_stride, int b_stride, int b_scale_stride)
     * }
     */
    public static int tensor2_gemm_i8_q4(MemorySegment result, MemorySegment a, MemorySegment a_scales, MemorySegment b, MemorySegment b_scales, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int a_scale_stride, int b_stride, int b_scale_stride) {
        var mh$ = tensor2_gemm_i8_q4.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tensor2_gemm_i8_q4", result, a, a_scales, b, b_scales, result_rows, a_row_offset, a_column_offset, b_column_offset, column_length, result_row_offset, b_row_offset, row_chunk_size, result_stride, a_stride, a_scale_stride, b_stride, b_scale_stride);
            }
            return (int)mh$.invokeExact(result, a, a_scales, b, b_scales, result_rows, a_row_offset, a_column_offset, b_column_offset, column_length, result_row_offset, b_row_offset, row_chunk_size, result_stride, a_stride, a_scale_stride, b_stride, b_scale_stride);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tensor2_batch_dot_f32_q8 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Tensor2Native.C_INT,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("tensor2_batch_dot_f32_q8");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * tensor2_status tensor2_batch_dot_f32_q8(float *result, const float *a, const int8_t *b, const float *b_scales, int result_rows, int b_rows, int column_length, int result_stride, int a_stride, int b_stride, int b_scale_stride)
     * }
     */
    public static FunctionDescriptor tensor2_batch_dot_f32_q8$descriptor() {
        return tensor2_batch_dot_f32_q8.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * tensor2_status tensor2_batch_dot_f32_q8(float *result, const float *a, const int8_t *b, const float *b_scales, int result_rows, int b_rows, int column_length, int result_stride, int a_stride, int b_stride, int b_scale_stride)
     * }
     */
    public static MethodHandle tensor2_batch_dot_f32_q8$handle() {
        return tensor2_batch_dot_f32_q8.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * tensor2_status tensor2_batch_dot_f32_q8(float *result, const float *a, const int8_t *b, const float *b_scales, int result_rows, int b_rows, int column_length, int result_stride, int a_stride, int b_stride, int b_scale_stride)
     * }
     */
    public static MemorySegment tensor2_batch_dot_f32_q8$address() {
        return tensor2_batch_dot_f32_q8.ADDR;
    }

    /**
     * {@snippet lang=c :
     * tensor2_status tensor2_batch_dot_f32_q8(float *result, const float *a, const int8_t *b, const float *b_scales, int result_rows, int b_rows, int column_length, int result_stride, int a_stride, int b_stride, int b_scale_stride)
     * }
     */
    public static int tensor2_batch_dot_f32_q8(MemorySegment result, MemorySegment a, MemorySegment b, MemorySegment b_scales, int result_rows, int b_rows, int column_length, int result_stride, int a_stride, int b_stride, int b_scale_stride) {
        var mh$ = tensor2_batch_dot_f32_q8.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tensor2_batch_dot_f32_q8", result, a, b, b_scales, result_rows, b_rows, column_length, result_stride, a_stride, b_stride, b_scale_stride);
            }
            return (int)mh$.invokeExact(result, a, b, b_scales, result_rows, b_rows, column_length, result_stride, a_stride, b_stride, b_scale_stride);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tensor2_scale_f32 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Tensor2Native.C_INT,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_FLOAT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("tensor2_scale_f32");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * tensor2_status tensor2_scale_f32(float *target, float factor, int rows, int offset, int length, int stride)
     * }
     */
    public static FunctionDescriptor tensor2_scale_f32$descriptor() {
        return tensor2_scale_f32.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * tensor2_status tensor2_scale_f32(float *target, float factor, int rows, int offset, int length, int stride)
     * }
     */
    public static MethodHandle tensor2_scale_f32$handle() {
        return tensor2_scale_f32.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * tensor2_status tensor2_scale_f32(float *target, float factor, int rows, int offset, int length, int stride)
     * }
     */
    public static MemorySegment tensor2_scale_f32$address() {
        return tensor2_scale_f32.ADDR;
    }

    /**
     * {@snippet lang=c :
     * tensor2_status tensor2_scale_f32(float *target, float factor, int rows, int offset, int length, int stride)
     * }
     */
    public static int tensor2_scale_f32(MemorySegment target, float factor, int rows, int offset, int length, int stride) {
        var mh$ = tensor2_scale_f32.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tensor2_scale_f32", target, factor, rows, offset, length, stride);
            }
            return (int)mh$.invokeExact(target, factor, rows, offset, length, stride);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tensor2_scale_bf16 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Tensor2Native.C_INT,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_FLOAT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("tensor2_scale_bf16");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * tensor2_status tensor2_scale_bf16(uint16_t *target, float factor, int rows, int offset, int length, int stride)
     * }
     */
    public static FunctionDescriptor tensor2_scale_bf16$descriptor() {
        return tensor2_scale_bf16.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * tensor2_status tensor2_scale_bf16(uint16_t *target, float factor, int rows, int offset, int length, int stride)
     * }
     */
    public static MethodHandle tensor2_scale_bf16$handle() {
        return tensor2_scale_bf16.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * tensor2_status tensor2_scale_bf16(uint16_t *target, float factor, int rows, int offset, int length, int stride)
     * }
     */
    public static MemorySegment tensor2_scale_bf16$address() {
        return tensor2_scale_bf16.ADDR;
    }

    /**
     * {@snippet lang=c :
     * tensor2_status tensor2_scale_bf16(uint16_t *target, float factor, int rows, int offset, int length, int stride)
     * }
     */
    public static int tensor2_scale_bf16(MemorySegment target, float factor, int rows, int offset, int length, int stride) {
        var mh$ = tensor2_scale_bf16.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tensor2_scale_bf16", target, factor, rows, offset, length, stride);
            }
            return (int)mh$.invokeExact(target, factor, rows, offset, length, stride);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tensor2_exp_f32 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Tensor2Native.C_INT,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("tensor2_exp_f32");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * tensor2_status tensor2_exp_f32(const float *input, float *output, int rows, int offset, int length, int input_stride, int output_stride)
     * }
     */
    public static FunctionDescriptor tensor2_exp_f32$descriptor() {
        return tensor2_exp_f32.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * tensor2_status tensor2_exp_f32(const float *input, float *output, int rows, int offset, int length, int input_stride, int output_stride)
     * }
     */
    public static MethodHandle tensor2_exp_f32$handle() {
        return tensor2_exp_f32.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * tensor2_status tensor2_exp_f32(const float *input, float *output, int rows, int offset, int length, int input_stride, int output_stride)
     * }
     */
    public static MemorySegment tensor2_exp_f32$address() {
        return tensor2_exp_f32.ADDR;
    }

    /**
     * {@snippet lang=c :
     * tensor2_status tensor2_exp_f32(const float *input, float *output, int rows, int offset, int length, int input_stride, int output_stride)
     * }
     */
    public static int tensor2_exp_f32(MemorySegment input, MemorySegment output, int rows, int offset, int length, int input_stride, int output_stride) {
        var mh$ = tensor2_exp_f32.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tensor2_exp_f32", input, output, rows, offset, length, input_stride, output_stride);
            }
            return (int)mh$.invokeExact(input, output, rows, offset, length, input_stride, output_stride);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tensor2_sum_f32 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Tensor2Native.C_FLOAT,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("tensor2_sum_f32");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * float tensor2_sum_f32(const float *input, int row, int offset, int length, int input_stride)
     * }
     */
    public static FunctionDescriptor tensor2_sum_f32$descriptor() {
        return tensor2_sum_f32.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * float tensor2_sum_f32(const float *input, int row, int offset, int length, int input_stride)
     * }
     */
    public static MethodHandle tensor2_sum_f32$handle() {
        return tensor2_sum_f32.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * float tensor2_sum_f32(const float *input, int row, int offset, int length, int input_stride)
     * }
     */
    public static MemorySegment tensor2_sum_f32$address() {
        return tensor2_sum_f32.ADDR;
    }

    /**
     * {@snippet lang=c :
     * float tensor2_sum_f32(const float *input, int row, int offset, int length, int input_stride)
     * }
     */
    public static float tensor2_sum_f32(MemorySegment input, int row, int offset, int length, int input_stride) {
        var mh$ = tensor2_sum_f32.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tensor2_sum_f32", input, row, offset, length, input_stride);
            }
            return (float)mh$.invokeExact(input, row, offset, length, input_stride);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

