// Generated by jextract

package io.teknek.deliverance.tensor.operations.tensor2native;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class Tensor2Native extends Tensor2Native$shared {

    Tensor2Native() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    private static final int TENSOR2_OK = (int)0L;
    /**
     * {@snippet lang=c :
     * enum tensor2_status.TENSOR2_OK = 0
     * }
     */
    public static int TENSOR2_OK() {
        return TENSOR2_OK;
    }
    private static final int TENSOR2_UNSUPPORTED = (int)1L;
    /**
     * {@snippet lang=c :
     * enum tensor2_status.TENSOR2_UNSUPPORTED = 1
     * }
     */
    public static int TENSOR2_UNSUPPORTED() {
        return TENSOR2_UNSUPPORTED;
    }

    private static class tensor2_batch_dot_f32_f32 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Tensor2Native.C_INT,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("tensor2_batch_dot_f32_f32");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * tensor2_status tensor2_batch_dot_f32_f32(float *result, const float *a, const float *b, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int b_stride)
     * }
     */
    public static FunctionDescriptor tensor2_batch_dot_f32_f32$descriptor() {
        return tensor2_batch_dot_f32_f32.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * tensor2_status tensor2_batch_dot_f32_f32(float *result, const float *a, const float *b, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int b_stride)
     * }
     */
    public static MethodHandle tensor2_batch_dot_f32_f32$handle() {
        return tensor2_batch_dot_f32_f32.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * tensor2_status tensor2_batch_dot_f32_f32(float *result, const float *a, const float *b, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int b_stride)
     * }
     */
    public static MemorySegment tensor2_batch_dot_f32_f32$address() {
        return tensor2_batch_dot_f32_f32.ADDR;
    }

    /**
     * {@snippet lang=c :
     * tensor2_status tensor2_batch_dot_f32_f32(float *result, const float *a, const float *b, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int b_stride)
     * }
     */
    public static int tensor2_batch_dot_f32_f32(MemorySegment result, MemorySegment a, MemorySegment b, int result_rows, int a_row_offset, int a_column_offset, int b_column_offset, int column_length, int result_row_offset, int b_row_offset, int row_chunk_size, int result_stride, int a_stride, int b_stride) {
        var mh$ = tensor2_batch_dot_f32_f32.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tensor2_batch_dot_f32_f32", result, a, b, result_rows, a_row_offset, a_column_offset, b_column_offset, column_length, result_row_offset, b_row_offset, row_chunk_size, result_stride, a_stride, b_stride);
            }
            return (int)mh$.invokeExact(result, a, b, result_rows, a_row_offset, a_column_offset, b_column_offset, column_length, result_row_offset, b_row_offset, row_chunk_size, result_stride, a_stride, b_stride);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tensor2_batch_dot_f32_q8 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Tensor2Native.C_INT,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_POINTER,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT,
            Tensor2Native.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("tensor2_batch_dot_f32_q8");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * tensor2_status tensor2_batch_dot_f32_q8(float *result, const float *a, const int8_t *b, const float *b_scales, int result_rows, int b_rows, int column_length, int result_stride, int a_stride, int b_stride, int b_scale_stride)
     * }
     */
    public static FunctionDescriptor tensor2_batch_dot_f32_q8$descriptor() {
        return tensor2_batch_dot_f32_q8.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * tensor2_status tensor2_batch_dot_f32_q8(float *result, const float *a, const int8_t *b, const float *b_scales, int result_rows, int b_rows, int column_length, int result_stride, int a_stride, int b_stride, int b_scale_stride)
     * }
     */
    public static MethodHandle tensor2_batch_dot_f32_q8$handle() {
        return tensor2_batch_dot_f32_q8.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * tensor2_status tensor2_batch_dot_f32_q8(float *result, const float *a, const int8_t *b, const float *b_scales, int result_rows, int b_rows, int column_length, int result_stride, int a_stride, int b_stride, int b_scale_stride)
     * }
     */
    public static MemorySegment tensor2_batch_dot_f32_q8$address() {
        return tensor2_batch_dot_f32_q8.ADDR;
    }

    /**
     * {@snippet lang=c :
     * tensor2_status tensor2_batch_dot_f32_q8(float *result, const float *a, const int8_t *b, const float *b_scales, int result_rows, int b_rows, int column_length, int result_stride, int a_stride, int b_stride, int b_scale_stride)
     * }
     */
    public static int tensor2_batch_dot_f32_q8(MemorySegment result, MemorySegment a, MemorySegment b, MemorySegment b_scales, int result_rows, int b_rows, int column_length, int result_stride, int a_stride, int b_stride, int b_scale_stride) {
        var mh$ = tensor2_batch_dot_f32_q8.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tensor2_batch_dot_f32_q8", result, a, b, b_scales, result_rows, b_rows, column_length, result_stride, a_stride, b_stride, b_scale_stride);
            }
            return (int)mh$.invokeExact(result, a, b, b_scales, result_rows, b_rows, column_length, result_stride, a_stride, b_stride, b_scale_stride);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}
