deliverance-model.configs[0].modelName=TinyLlama-1.1B-Chat-v1.0-Jlama-Q4
deliverance-model.configs[0].modelOwner=tjake
deliverance-model.configs[0].inferenceType=GENERATION

deliverance-model.configs[1].modelName=all-MiniLM-L6-v2
deliverance-model.configs[1].modelOwner=sentence-transformers
deliverance-model.configs[1].inferenceType=EMBEDDING
