#!/usr/bin/env sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

DELIVERANCE_DEAD_TO_RIGHTS_BASE_URL=${DELIVERANCE_DEAD_TO_RIGHTS_BASE_URL:-http://localhost:${DELIVERANCE_DEAD_TO_RIGHTS_PORT:-18087}} \
DELIVERANCE_DEAD_TO_RIGHTS_MODEL=${DELIVERANCE_DEAD_TO_RIGHTS_MODEL:-Qwen3-0.6B-JQ4} \
DELIVERANCE_DEAD_TO_RIGHTS_MAX_TOKENS=${DELIVERANCE_DEAD_TO_RIGHTS_MAX_TOKENS:-384} \
"$SCRIPT_DIR/run-dead-to-rights.sh" "$@"
