deliverance.tensor.operations.type=simd

deliverance-model.configs[0].model-owner=tjake
deliverance-model.configs[0].model-name=Llama-3.2-3B-Instruct-JQ4
deliverance-model.configs[0].inference-type=GENERATION
