deliverance.tensor.operations.type=simd

deliverance-model.configs[0].model-owner=edwardcapriolo
deliverance-model.configs[0].model-name=Qwen3-4B-JQ4
deliverance-model.configs[0].inference-type=GENERATION
deliverance-model.configs[0].output-head-quantization=Q4
