deliverance.tensor.operations.type=jvector

deliverance-model.configs[0].model-owner=tjake
deliverance-model.configs[0].model-name=TinyLlama-1.1B-Chat-v1.0-Jlama-Q4
deliverance-model.configs[0].inference-type=GENERATION
